name: "Mise init"
description: "Initialise an environment with the repository and Mise"

inputs:
  install-args:
    description: "List of tools to install. If left blank all tooling is installed"
    default: "just"
    required: false
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Install Mise
      shell: bash
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        mise trust
        mise install ${{ inputs.install-args }}
