version: "3.8"
services:
  piped-bot:
    container_name: piped_bot
    env_file: ./bot/.env
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    expose:
      - "80:80"
    networks:
      - "piped"

networks:
  piped:
    name: piped
