set shell := ["mise", "exec", "--", "bash", "-o", "errexit", "-uc"]

artifacts_dir := "./artifacts"
project_name := "${PROJECT_NAME:-}"

default:
    just --list

# Build this project using flit
[group("build")]
[group("build-python")]
build-python:
    target_dir="${{ artifacts_dir }}/dist"
    uv run --only-group=publish flit build
    rm -fr "$target_dir"
    mv -r "./dist" "$target_dir"

# Cleanup any temporary files made in this project by its nox tasks
cleanup:
    python ./scripts/cleanup.py

# Task which combines the coverage reports generated by test-cov
combine-coverage:
    function coverage() {
    uv exec --group=coverage coverage $@
    }

    report_file="${{ artifacts_dir }}/.coverage"
    rm -f "$report_file"

    while read -r -d $'\0' path; do
    echo "Adding $path to coverage report"
    coverage combine "--data-file" "$report_file" "$path"
    done < <(find "{{ artifacts_dir }}/coverage/" -type f -name "**/*.coverage*" -print0)

    coverage xml -o "${{ artifacts_dir }}/coverage.xml" --data-file "$report_file"
    coverage report --data-file "$report_file"

# Reformat this project's modules to fit the standard style
[group("format")]
[group("format python")]
format-python:
    uv run --only-group=reformat black .
    uv run --only-group=reformat isort .
    uv run --only-group=reformat pycln --config pyproject.toml .
    uv run --only-group=reformat sort-all || echo "Sorted alls"
    # TODO:
    # session.run("python", "-m", "pre_commit_hooks.end_of_file_fixer", *tracked_files, success_codes=[0, 1], log=False)

    # session.log("Running pre_commit_hooks.trailing_whitespace_fixer")
    # session.run(
    #     "python", "-m", "pre_commit_hooks.trailing_whitespace_fixer", *tracked_files, success_codes=[0, 1], log=False
    # )

# Freeze the dependency locks
freeze-locks:
    uv lock --upgrade

# Generate docs for this project using Mkdoc.
generate-docs:
    target_dir="${{ artifacts_dir }}/site"
    rm -fr "$target_dir"
    mkdir -p "$target_dir"
    uv run --only-group=docs mkdocs build --strict -d "$target_dir"

# Publish this project to pypi
publish-python:
    if [[ -z "${PUBLISH_TARGET:-}" ]]
    then
    export FLIT_INDEX_URL="$PUBLISH_TARGET" 
    fi

    if [[ -z "${PUBLISH_TOKEN:-}" ]]
    then
    export FLIT_PASSWORD="$PUBLISH_TOKEN" 
    fi

    export FLIT_USERNAME="${FLIT_USERNAME:-__token__}"
    uv run --only-group=publish flit publish

# Publish this project to test pypi
publish-test-python:
    export PYPI_TARGET="https://test.pypi.org/legacy/"
    just publish-python

# Run this project's modules against the pre-defined ruff linters
[group("lint")]
[group("lint python")]
lint-python:
    uv run --group=lint ruff check

# Check this project's slotted classes for common mistakes
[group("lint")]
[group("lint python")]
slot-check:
    yq - -p
    uv exec --group=lint slotscheck -v -m "$project_name"

# Check this project's text-like files for common spelling mistakes
[group("lint")]
[group("lint python")]
spell-check:
    codespell

# Run this project's tests using pytest
test-python:
    uv exec --group=test pytest -n auto --import-mode importlib

# Run this project's tests while recording test coverage
test-python-cov:
    target_xml="${{ artifacts_dir }}/coverage.xml"
    target_html="${{ artifacts_dir }}/coverage_html"
    target_report="${{ artifacts_dir }}/.coverage"
    uv exec --group=test \
    pytest \
    -n auto \
    --cov "$project_name" \
    --cov-report term \
    --cov-report "xml:$target_xml" \
    --cov-report "html:$target_html"

    rm -f "$target_report"
    mv "./.coverage" "$target_report"

# Bump the end year of the project's licence to the current year
[group("update-license")]
update-licence:
    python ./scripts/update_license.py

# TODO: verify_types
# TODO: bot_package_diff
# TODO: is_diff_file_empty
