name: "Install Python"
description: "Install a specific Python version"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: install-py
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Install Nox
      shell: bash
      run: |
        set +o pipefail

        pipx install uv nox[uv] --python "${{ steps.install-py.outputs.python-path }}"
