name: "Install Python"
description: "Install a specific Python version"
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.11"
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@3d1e2d2ca0a067f27da6fec484fce7f5256def85
      id: install-py
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Nox
      run: pipx install uv nox[uv] --python "${{ steps.install-py.outputs.python-path }}"
      shell: bash
