name: Build Container

on:
  schedule:
    - cron: "{{ CRON }}"
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: {% raw %}${{ github.repository }}{% endraw %}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 #v3.9.2

      - name: Install QEMU
        if: github.event_name != 'pull_request'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set platforms
        if: github.event_name != 'pull_request'
        env:
          CONTAINER_PLATFORMS: {{ CONTAINER_PLATFORMS | join(",") }}
        run: echo "CONTAINER_PLATFORMS=$CONTAINER_PLATFORMS" >> $GITHUB_ENV

      - name: Generate container metadata
        id: metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: {% raw %}${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}{% endraw %}

      - name: Build image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          tags: {% raw %}${{ steps.metadata.outputs.tags }}{% endraw %}
          labels: {% raw %}${{ steps.metadata.outputs.labels }}{% endraw %}
          platforms: {% raw %}${{ env.CONTAINER_PLATFORMS }}{% endraw %}
          containerfiles: |
            ./Containerfile
          context: {{ CONTAINER_BUILD_CONTEXT }}

      - name: Push image
        id: push-image
        if: {% raw %}${{ github.event_name != 'pull_request' }}{% endraw %}
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          tags: {% raw %}${{ steps.metadata.outputs.tags }}{% endraw %}
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      # This log in step is only required to allow signing the container iamge
      - name: Log into registry {% raw %}${{ env.REGISTRY }}{% endraw %}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: {% raw %}${{ env.REGISTRY }}{% endraw %}
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Sign the published container image
        if: {% raw %}${{ github.event_name != 'pull_request' }}{% endraw %}
        env:
          TAGS: {% raw %}${{ steps.metadata.outputs.tags }}{% endraw %}
          DIGEST: {% raw %}${{ steps.push-image.outputs.digest }}{% endraw %}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}{% endif %}
