name: Freeze PR dependency changes

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ (FILTERS + EXTEND_FILTERS) | map("quoted") | join(", ") }}]

jobs:
  freeze-pr-dep-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Upgrade dependency locks
        run: nox -s freeze-locks bot-package-diff

      - uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: gogo.patch
          path: |
            artifacts/gogo.patch
            gogo.patch

      - name: Check diff file
        run: nox -s is-diff-file-empty
