name: Deploy PR preview docs

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run generate-docs session
        if: github.event.action != 'closed'
        uses: ./.github/nox-sessions
        with:
          nox-sessions: generate-docs -- -o ./artifacts/site
          {% raw %}ref: ${{ github.event.pull_request.head.sha }}{% endraw %}
          {% raw %}repository: ${{ github.event.pull_request.head.repo.full_name }}{% endraw %}

      - name: Deploy preview
        uses: FasterSpeeding/pr-preview-action@task/override-committer
        with:
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
          preview-branch: docs
          source-dir: ./artifacts/site/
