name: Run tests

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        os: [{{ OSES | join(", ") }}]
        python-version: [{{ PYTHON_VERSIONS | map("format_string", '"{}"') | join(", ") }}]

    {% raw %}runs-on: ${{ matrix.os }}{% endraw %}

    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"{% if REQUIRES_RUST %}
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
            toolchain: nightly
            override: true
{% endif %}
      - name: Run test session
        uses: ./.github/actions/nox-sessions
        with:
          nox-sessions: test-coverage
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Create coverage artifacts
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: {% raw %}.coverage.${{ matrix.os }}.${{ matrix.python-version }}{% endraw %}
          path: artifacts/.coverage
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  upload-coverage:
    needs: [py-test]
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          pattern: .coverage.*
          merge-multiple: false
          path: ./artifacts/coverage/
          recurse_submodules: true

      - name: Run combine-coverage session
        uses: ./.github/actions/nox-sessions
        with:
          nox-sessions: combine-coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          files: ./artifacts/coverage.xml
          use_oidc: true

      - name: Create coverage artifacts
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: .coverage.combined
          path: |
            artifacts/coverage.xml
            artifacts/coverage_html
          include-hidden-files: true
          if-no-files-found: error
