name: Reformat PR code

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
      - name: Run reformat session
        uses: ./.github/actions/nox-sessions
        with:
          nox-sessions: reformat bot-package-diff

      - name: Check diff file
        uses: ./.github/actions/handle-diff-file
