name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:{% if BRANCH_PUSHES  %}
  push:
    branches: [{{ BRANCH_PUSHES | join(", ") }}]{% endif %}

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          nox -s generate-docs -- -o ./site -j
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_STATE

      - name: Push
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a
        with:
          branch: docs
          {% raw %}commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"{% endraw %}
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
