name: Resync piped

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ FILTERS | map("format_string", '"{}"') | join(", ") }}]

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - name: Run copy-piped session
        uses: ./.github/nox-sessions
        with:
          nox-sessions: copy-piped bot-package-diff

      - name: Check diff file
        uses: ./.github/handle-diff-file
