name: Resync piped

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ FILTERS | map("quoted") | join(", ") }}]

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Resync Piped
        run: nox -s copy-piped bot-package-diff

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: nox -s is-diff-file-empty
