name: Run Rustfmt

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on: pull_request

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Reformat
        run: cargo +nightly fmt

      - name: Package
        run: nox -s bot-package-diff

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: nox -s is-diff-file-empty
