name: Update licence

on:
  schedule:
    - cron: "{{ CRON }}"
  workflow_dispatch:

jobs:
  update-licence:
    runs-on: ubuntu-latest

    steps:
      - name: Run update-licence session
        uses: ./.github/actions/nox-sessions
        with:
          nox-sessions: update-licence

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18e469570b1cf0dfc11d60ec121099f8ff3e617a
        with:
          author: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          branch: task/update-licence
          commit-message: Update licence
          committer: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          title: Update licence
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
