name: Upgrade dependency locks

on:
  schedule:
    - cron: "{{ CRON }}"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Run freeze-locks session
        uses: ./.github/nox-sessions.yml
        with:
          nox-sessions: freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18e469570b1cf0dfc11d60ec121099f8ff3e617a
        with:
          author: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          title: Upgrade dependency locks
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
