name: "Handle diff file"
description: "Handle any created diff files"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
      with:
        name: gogo.patch
        path: |
          artifacts/gogo.patch
          gogo.patch

    - name: Check diff file
      run: nox -s is-diff-file-empty
