name: "Just jobs"
description: "Run a Just job"

inputs:
  task-names:
    description: "Names of the tasks to run"
    required: true
  extra-installs:
    description: "List of extra tools to install alongside Just using mise"
    default: ""
    required: false
  repository:
    description: "The repository's name"
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Initialise environment with Mise
      uses: FasterSpeeding/Piped/.github/actions/mise-init@master
      with:
        install-args: "just ${{ inputs.extra-installs }}"
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Run Just jobs
      shell: bash
      env:
        INSTALL_DEV_DEPS: true
      run: |
        set +o pipefail

        mise env -s bash | just ${{ inputs.task-names }}
