name: Freeze PR dependency changes

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ (FILTERS + EXTEND_FILTERS) | map("quoted") | join(", ") }}]

jobs:
  freeze-pr-dep-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.ref }}{% endraw %}
          {% raw %}repository: ${{ github.event.pull_request.head.repo.full_name }}{% endraw %}
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks bot-package-diff

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: python -m nox -s is-diff-file-empty
