name: Freeze PR dependency changes

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ (FILTERS + EXTEND_FILTERS) | map("quoted") | join(", ") }}]

jobs:
  freeze-pr-dep-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks bot-package-diff

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: python -m nox -s is-diff-file-empty
