name: Lint

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}{% if "verify-markup" not in config.hide %}

      - name: Lint markup
        run: python -m nox -s verify-markup{% endif %}{% if "spell-check" not in config.hide %}

      - name: Check spelling
        run: python -m nox -s spell-check{% endif %}{% if "flake8" not in config.hide %}

      - name: Lint with flake8
        run: python -m nox -s flake8{% endif %}{% if "slot-check" not in config.hide %}

      - name: Check slotting
        run: python -m nox -s slot-check{% endif %}
