name: Deploy PR preview docs

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch merge branch
        uses: actions/checkout@v3
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.sha }}{% endraw %}
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        if: github.event.action != 'closed'
        uses: actions/setup-python@v4
        with:
          python-version: {{ DEFAULT_PY_VER }}

      - name: install prerequisites
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Build docs
        if: github.event.action != 'closed'
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          preview-branch: docs
