name: Deploy PR preview docs

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch merge branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.sha }}{% endraw %}
          {% raw %}repository: ${{ github.event.pull_request.head.repo.full_name }}{% endraw %}
          submodules: "true"

      - name: Install Python
        uses: ./.github/workflows/setup-py.yml

      - name: Build docs
        if: github.event.action != 'closed'
        run: |
          mkdir site
          nox -s generate-docs -- -o ./site

      - name: Deploy preview
        uses: FasterSpeeding/pr-preview-action@task/override-committer
        with:
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
          preview-branch: docs
          source-dir: ./site/
