name: Deploy PR preview docs

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch merge branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.sha }}{% endraw %}
          {% raw %}repository: ${{ github.event.pull_request.head.repo.full_name }}{% endraw %}
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        if: github.event.action != 'closed'
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Build docs
        if: github.event.action != 'closed'
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site

      - name: Deploy preview
        uses: FasterSpeeding/pr-preview-action@task/override-committer
        with:
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
          preview-branch: docs
          source-dir: ./site/
