name: Publish a new release

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types:
      - published

jobs:
  publish-docs:
    uses: ./.github/workflows/release-docs.yml

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python {{DEFAULT_PY_VER}}
        uses: actions/setup-python@v4
        with:
          python-version: {{DEFAULT_PY_VER}}

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{NOX_DEP_PATH}}

      - name: publish
        run: python -m nox -s publish
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
