name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        os: {{OSES}}
        python-version: {{PYTHON_VERSIONS}}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{NOX_DEP_PATH}}

      - name: Run tests
        run: |
          python -m nox -s test

  # TODO: Could we switch over to gather coverage from the normal test runs and combining
  # the result once https://github.com/nedbat/coveragepy/issues/1002 is fixed?
  upload-coverage:
    # needs: [test]
    if: '{{CODECLIMATE_TOKEN}}' != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python 3.9  # 10
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # 10

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{NOX_DEP_PATH}}

      - name: Record coverage
        run: |
          python -m nox -s test-coverage

      - name: Upload coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: {{CODECLIMATE_TOKEN}}
        with:
          coverageLocations: .coverage.xml:coverage.py

      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage_html
          if-no-files-found: error
