name: Run tests

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        os: {{ OSES }}
        python-version: [{{ PYTHON_VERSIONS | map("quoted") | join(", ") }}]

    {% raw %}runs-on: ${{ matrix.os }}{% endraw %}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: "true"

      {% raw %}- name: Set up Python ${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          {% raw %}python-version: ${{ matrix.python-version }}{% endraw %}

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Run tests
        run: |
          python -m nox -s test{% if CODECLIMATE_TOKEN %}

  # TODO: Could we switch over to gather coverage from the normal test runs and combining
  # the result once https://github.com/nedbat/coveragepy/issues/1002 is fixed?
  upload-coverage:
    # needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Record coverage
        run: |
          python -m nox -s test-coverage

      - name: Upload coverage
        uses: paambaati/codeclimate-action@a1831d7162ea1fbc612ffe5fb3b90278b7999d59
        env:
          CC_TEST_REPORTER_ID: {{ CODECLIMATE_TOKEN }}
        with:
          coverageLocations: .coverage.xml:coverage.py

      - name: Archive coverage
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
        with:
          name: coverage
          path: ./coverage_html
          if-no-files-found: error{% endif %}
