name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:{% if BRANCH_PUSHES  %}
  push:
    branches: [{{ BRANCH_PUSHES | join(", ") }}]{% endif %}

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site -j
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_STATE

      - name: Push
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          branch: docs
          {% raw %}commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"{% endraw %}
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
