name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:{% if BRANCH_PUSHES  %}
  push:
    branches: [{{ BRANCH_PUSHES | join(", ") }}]{% endif %}

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site -j
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_STATE

      - name: Push
        uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0
        with:
          branch: docs
          {% raw %}commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"{% endraw %}
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "{{ ACTION_COMMITTER_EMAIL }}"
          git-config-name: "{{ ACTION_COMMITTER_USERNAME }}"
