name: Resync piped

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths:
      - piped
      - pyproject.toml

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.ref }}{% endraw %}
          submodules: "true"
          {% raw %}token: ${{ secrets.WORKFLOW_TOKEN }}{% endraw %}

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: {{ DEFAULT_PY_VER }}

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Resync Piped
        run: python -m nox -s copy-actions

      - name: Freeze dependency locks
        run: python -m nox -s freeze-locks

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Resync piped
