name: Resync piped

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: [{{ FILTERS | map("quoted") | join(", ") }}]

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          {% raw %}ref: ${{ github.event.pull_request.head.ref }}{% endraw %}
          {% raw %}repository: ${{ github.event.pull_request.head.repo.full_name }}{% endraw %}
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Resync Piped
        run: python -m nox -s copy-piped bot-package-diff

      - uses: actions/upload-artifact@v3
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: python -m nox -s is-diff-file-empty
