name: Run Rustfmt

concurrency:
  {% raw %}group: ${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on: pull_request

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./piped/python/base-requirements/nox.txt

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Reformat
        run: cargo +nightly fmt

      - name: Package
        run: python -m nox -s bot-package-diff

      - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: python -m nox -s is-diff-file-empty
