name: Update license

on:
  schedule:
    - cron: "0 7 * 1 0"
  workflow_dispatch:

jobs:
  update-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Update license
        run: python -m nox -s update-license

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          title: Upgrade dependency locks
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
