name: Upgrade dependency locks

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          title: Upgrade dependency locks
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN }}{% endraw %}
