name: Upgrade dependency locks

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6cd32fd93684475c31847837f87bb135d40a2b79
        with:
          author: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          title: Upgrade dependency locks
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
