name: Upgrade dependency locks

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
        with:
          submodules: "true"

      - name: Set up Python {{ DEFAULT_PY_VER }}
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "{{ DEFAULT_PY_VER }}"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r {{ NOX_DEP_PATH }}

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e
        with:
          author: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "{{ ACTION_COMMITTER_USERNAME }} <{{ ACTION_COMMITTER_EMAIL }}>"
          title: Upgrade dependency locks
          {% raw %}token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
