[project]
name = "piped"
requires-python = ">=3.11"
version = "0.1.0"
dependencies = [
    "asgiref",
    "fastapi",
    "httpx[http2]",
    "jwt",
    "python-dateutil",
    "python-dotenv",
    "uvicorn",
    "uvloop; platform_system != 'Windows'",
]
