name: "Install Python"
description: "Install a specific Python version"
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "{{ DEFAULT_PY_VER }}"
runs:
  using: composite
  steps:
    - name: Set up Python {% raw %}${{ inputs.python-version }}{% endraw %}
      uses: actions/setup-python@3d1e2d2ca0a067f27da6fec484fce7f5256def85
      id: install-py
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: Install Nox
      run: pipx install uv nox[uv] --python {% raw %}"${{ steps.install-py.outputs.python-path }}"{% endraw %}
      shell: bash
