name: Run clippy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialise environment with Mise
        uses: FasterSpeeding/Piped-actions/.github/actions/mise-init@52f3085b5624714efc892fab2d486451bd4c1742 # 2026.03.07
        with:
          install-args: rust

      - uses: auguwu/clippy-action@9817d076b82df0194935be9db6154c56ac07b317 # 1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
