name: Deploy PR preview docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      committer-email:
        description: "The email address to use for doc branch commits"
        default: 120557446+always-on-duty[bot]@users.noreply.github.com
        required: false
        type: string
      committer-username:
        description: "The username address to use for doc branch commits"
        default: always-on-duty[bot]
        required: false
        type: string

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: "true"

      - name: Run generate-docs
        if: github.event.action != 'closed'
        uses: FasterSpeeding/Piped/.github/actions/nox-sessions@master
        with:
          nox-sessions: generate-docs -- -o ./artifacts/site

      - name: Deploy preview
        uses: FasterSpeeding/pr-preview-action@task/override-committer
        with:
          git-config-email: "${{ inputs.committer-email }}"
          git-config-name: "${{ inputs.committer-username }}"
          preview-branch: docs
          source-dir: ./artifacts/site/

      - name: Check diff file
        uses: FasterSpeeding/Piped/.github/actions/handle-diff-file@master
