name: Deploy PR preview docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      committer-email:
        description: "The email address to use for doc branch commits"
        default: 120557446+always-on-duty[bot]@users.noreply.github.com
        required: false
        type: string
      committer-username:
        description: "The username address to use for doc branch commits"
        default: always-on-duty[bot]
        required: false
        type: string

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run generate-docs job
        if: github.event.action != 'closed'
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@e3e3d62e42bae0a3607b2735c57c3c1fc851a224 # 2025.10.02
        with:
          extra-installs: python uv
          task-names: generate-docs
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Deploy preview
        uses: FasterSpeeding/pr-preview-action@task/override-committer
        with:
          git-config-email: "${{ inputs.committer-email }}"
          git-config-name: "${{ inputs.committer-username }}"
          preview-branch: docs
          source-dir: ./artifacts/site/

      - name: Check diff file
        uses: FasterSpeeding/Piped-actions/.github/actions/handle-diff-file@e3e3d62e42bae0a3607b2735c57c3c1fc851a224 # 2025.10.02
