name: Publish a new release

on:
  workflow_call:

jobs:
  publish:
    name: upload release to PyPI
    runs-on: ubuntu-24.04
    environment: release

    permissions:
      id-token: write

    steps:
      - name: Run build-python job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@475df54c30e176ecd3c102808b10c735f4d50850 # 2026.04.09
        with:
          extra-installs: python uv pipx:flit
          task-names: build-python

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
