name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise alongside Python (i.e. Rust for builds)"
        default: ""
        required: false
        type: string
      os-versions:
        description: "Json array of the runner OSes to test against"
        default: '["ubuntu-24.04-arm", "macos-latest", "windows-latest"]'
        required: false
        type: string
      python-versions:
        description: "Json array of the Python versions to test against"
        default: '["3.11", "3.12", "3.13"]'
        required: false
        type: string

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        runner-os: ${{ fromJSON(inputs.os-versions) }}
        python-version: ${{ fromJSON(inputs.python-versions) }}

    runs-on: ${{ matrix.runner-os }}

    steps:
      - name: Run test job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@52f3085b5624714efc892fab2d486451bd4c1742 # 2026.03.07
        env:
          TEST_PYTHON_VERSION: "${{ matrix.python-version }}"
        with:
          extra-installs: "python@${{ matrix.python-version }} uv ${{ inputs.extra-installs }}"
          task-names: test-python-cov

      - name: Create coverage artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: .coverage.${{ matrix.runner-os }}.${{ matrix.python-version }}
          path: artifacts/.coverage
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  upload-coverage:
    needs: [py-test]
    runs-on: ubuntu-24.04

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: .coverage.*
          merge-multiple: false
          path: ./artifacts/coverage/

      - name: Run combine-coverage job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@52f3085b5624714efc892fab2d486451bd4c1742 # 2026.03.07
        with:
          extra-installs: python uv
          task-names: combine-coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          files: ./artifacts/coverage.xml
          use_oidc: true

      - name: Create coverage artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: .coverage.combined
          path: |
            artifacts/coverage.xml
            artifacts/coverage_html
          include-hidden-files: true
          if-no-files-found: error
