name: Resync piped

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: ["github/actions/**", "github/workflows/*", "pyproject.toml"]

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - name: Run copy-piped session
        uses: ./.github/nox-sessions.yml
        with:
          nox-sessions: copy-piped bot-package-diff

      - name: Check diff file
        uses: ./.github/handle-diff-file.yml
