name: Resync piped

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths:
      - piped
      - pyproject.toml

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: "true"

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./python/base-requirements/nox.txt

      - name: Resync Piped
        run: python -m nox -s copy-actions

      - name: Freeze dependency locks
        run: python -m nox -s freeze-locks

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Resync piped
