name: Type check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise (i.e. Rust for builds)"
        default: ""
        required: false
        type: string

jobs:
  type-check:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Run type-check-python job
        uses: FasterSpeeding/Piped/.github/actions/just-jobs@task/justfile
        with:
          extra-installs: "${{ inputs.extra-installs }}"
          task-names: type-check-python
