name: Type check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      rust-toolchain:
        description: "If past, installed the specified rust toolchain for use during checks"
        default: ""
        required: false
        type: string

jobs:
  type-check:
    runs-on: ubuntu-20.24-arm

    steps:
      - name: Run type-check-python job
        uses: FasterSpeeding/Piped/.github/actions/just-jobs@task/justfile
        with:
          install-args: ""
          task-names: type-check-python
