name: Type check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise alongside python (i.e. Rust for builds)"
        default: ""
        required: false
        type: string

jobs:
  type-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Run type-check-python job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@73d410896bf35bcf14b2d875361b929a6cfea7e8 # 2025.10.04
        with:
          extra-installs: "node python uv npm:pyright ${{ inputs.extra-installs }}"
          task-names: type-check-python
