name: Type check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Run type-check session
        uses: ./.github/nox-sessions.yml
        with:
          nox-sessions: type-check
