name: Verify type-completeness

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise alongside Python (i.e. Rust for builds)"
        default: ""
        required: false
        type: string

jobs:
  verify-types:
    runs-on: ubuntu-24.04

    steps:
      - name: Run verify-types job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@475df54c30e176ecd3c102808b10c735f4d50850 # 2026.04.09
        with:
          extra-installs: "node python npm:pyright ${{ inputs.extra-installs }}"
          task-names: verify-types
